### ISSUE TITLE
R version on CEG Server

### ISSUE THREAD

**Issue by alexandriai168** [MMARINeDNA/metabarcoding_QAQC_pipeline#8]
If we want the pipeline to run on CEG, we need to iron out how to get a version of R on there that can run the Dada2QAQC script.  if I remember correctly, it can't install the seqinr package bc the version is too old.

Idk how we'd go about doing this, but maybe we could have a local version of R that we use (not really sure how to execute that)? Thoughts?

**Comment by invertdna** [comment]
Yep. We have to ask Chris B, the sysadmin for CEG.  He didn't want to update R because doing so would break things for other people. But we can ask again. R on the server is v 4.0.4 (from 2021), and maybe it's time. In the meantime, an earlier version of seqinr might be worth a shot. Here is the archive for those versions: https://cran.r-project.org/src/contrib/Archive/seqinr/

**Comment by eandrusz** [comment]
I think you can create an "environment" where you can have a different
version of R. See:
https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by avancise** [comment]
Anaconda has to be loaded on the HPC before you can set up conda
environments, but once it's set up then conda environments are a pretty
easy best practice, even if R is updated. They do take a lot of extra
storage space, since every conda environment has every software program
loaded as a separate instance, but so far I haven't encountered an HPC
manager who is against it (but might be good to ask 1) if it exists on the
CEG computer, and 2) can we reload cutadapt, R and all of its associated
packages in our own conda environment).


<*)))><  <*)))><  <*)))><  <*)))><  <*)))><  <*)))><  <*)))><  <*)))><
Amy M. Van Cise, Ph.D.
(she/her/hers)

Assistant Professor
Whale and Dolphin Ecology Lab <http://amyvancise.com>
University of Washington | School of Aquatic and Fisheries Sciences
1122 NE Boat St, Box 355020
Seattle, WA 98105
Office: SAFS 216B
206-221-6118

Need to meet with me? Let's find a time
<https://calendar.app.google/6S7FAok44L6n2TpF7>.

Where is Amy? [Spring 2023 edition]**
Monday: UW campus
Tuesday: hiding (focus day)
Wednesday: UW campus
Thursday: NOAA NWFSC Genetics lab
Friday: UW campus

**This is not exact. If you can't find me, shoot me an email and I will get
back to you.

**Comment by alexandriai168** [comment]
this has been fixed by developing a docker/singularity image that people can run on either their local machine or HPC.
